services:
  web:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: web_libreria
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    networks:
      - red1
    depends_on:
      - db

  
  db:
    image: mysql
    container_name: db_libreria
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootlib
      MYSQL_USER: miriam
      MYSQL_PASSWORD: libreria123
    volumes:
      - ./datos/:/var/lib/mysql
      - ./script/:/docker-entrypoint-initdb.d/
    networks:
      - red1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_libreria
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootlib
    ports:
      - "8081:80"
    networks:
      - red1
    depends_on:
      - db
    restart: unless-stopped 


volumes:
  datos:

networks:
  red1:
